SET client_encoding TO 'UTF8';

-- Dados reais GTFS importados de backend/src/main/resources/gtfs/routes.txt
INSERT INTO linhas (gtfs_route_id, numero, nome, origem, destino, num_paragens, duracao_min, cor) VALUES
('2', '2', 'Ponte De Prado - Bom Jesus', 'Ponte De Prado', 'Bom Jesus', 0, 0, '#ef4444'),
('3', '3', 'Avenida Central - Ruães', 'Avenida Central', 'Ruães', 0, 0, '#3b82f6'),
('5', '5', 'Dume - Quinta Da Capela', 'Dume', 'Quinta Da Capela', 0, 0, '#10b981'),
('6', '6', 'Avenida General Norton De Matos - Gondizalves/Semelhe', 'Avenida General Norton De Matos', 'Gondizalves/Semelhe', 0, 0, '#f59e0b'),
('7', '7', 'S. Mamede D'' Este - Celeirós', 'S. Mamede D'' Este', 'Celeirós', 0, 0, '#8b5cf6'),
('8', '8', 'Rua 25 De Abril - Sete Fontes', 'Rua 25 De Abril', 'Sete Fontes', 0, 0, '#ec4899'),
('9', '9', 'Ruães - Nogueira (Barral)', 'Ruães', 'Nogueira (Barral)', 0, 0, '#0077b6'),
('12', '12', 'Avenida Da Liberdade - Lageosa/Pedralva Via Gualtar', 'Avenida Da Liberdade', 'Lageosa/Pedralva Via Gualtar', 0, 0, '#ef4444'),
('13', '13', 'Avenida General Norton De Matos- Lageosa/Pedralva', 'Avenida General Norton De Matos- Lageosa/Pedralva', 'Avenida General Norton De Matos- Lageosa/Pedralva', 0, 0, '#3b82f6'),
('14', '14', 'Praça Conde De Agrolongo - Priscos', 'Praça Conde De Agrolongo', 'Priscos', 0, 0, '#10b981'),
('18', '18', 'Rua Do Raio - Pinheiro Do Bicho Via Esporões', 'Rua Do Raio', 'Pinheiro Do Bicho Via Esporões', 0, 0, '#f59e0b'),
('19', '19', 'Areal - Boavista', 'Areal', 'Boavista', 0, 0, '#8b5cf6'),
('20', '20', 'Avenida Da Liberdade - Escudeiros Via Ponte Nova', 'Avenida Da Liberdade', 'Escudeiros Via Ponte Nova', 0, 0, '#ec4899'),
('21', '21', 'Praça Conde De Agrolongo - Tadim', 'Praça Conde De Agrolongo', 'Tadim', 0, 0, '#0077b6'),
('23', '23', 'Avenida General Norton De Matos - Espinho/Sameiro', 'Avenida General Norton De Matos', 'Espinho/Sameiro', 0, 0, '#ef4444'),
('24', '24', 'Sequeira - Gualtar', 'Sequeira', 'Gualtar', 0, 0, '#3b82f6'),
('31', '31', 'Rua 25 De Abril - S. Mamede D'' Este (Rola)', 'Rua 25 De Abril', 'S. Mamede D'' Este (Rola)', 0, 0, '#10b981'),
('32', '32', 'Praça Conde De Agrolongo - Aveleda', 'Praça Conde De Agrolongo', 'Aveleda', 0, 0, '#f59e0b'),
('33', '33', 'Avenida Central - Cabreiros', 'Avenida Central', 'Cabreiros', 0, 0, '#8b5cf6'),
('34', '34', 'Avenida Da Liberdade - Guisande', 'Avenida Da Liberdade', 'Guisande', 0, 0, '#ec4899'),
('35', '35', 'Praça Conde De Agrolongo - Tebosa/Guisande', 'Praça Conde De Agrolongo', 'Tebosa/Guisande', 0, 0, '#0077b6'),
('36', '36', 'Avenida General Norton De Matos - S. Julião De Passos', 'Avenida General Norton De Matos', 'S. Julião De Passos', 0, 0, '#ef4444'),
('37', '37', 'Avenida General Norton De Matos - Cunha/Arentim', 'Avenida General Norton De Matos', 'Cunha/Arentim', 0, 0, '#3b82f6'),
('38', '38', 'Rua Do Raio - Morreira', 'Rua Do Raio', 'Morreira', 0, 0, '#10b981'),
('39', '39', 'Rua Do Raio - Trandeiras Via Esporões', 'Rua Do Raio', 'Trandeiras Via Esporões', 0, 0, '#f59e0b'),
('40', '40', 'Circuito Urbano I', 'Circuito Urbano I', 'Circuito Urbano I', 0, 0, '#8b5cf6'),
('41', '41', 'Circuito Urbano Ii', 'Circuito Urbano Ii', 'Circuito Urbano Ii', 0, 0, '#ec4899'),
('42', '42', 'Residência Universitária - Universidade Do Minho', 'Residência Universitária', 'Universidade Do Minho', 0, 0, '#0077b6'),
('43', '43', 'Estação Cf - Universidade Do Minho', 'Estação Cf', 'Universidade Do Minho', 0, 0, '#ef4444'),
('45', '45', 'Nogueira (Hospital Privado) - Ponte Do Bico', 'Nogueira (Hospital Privado)', 'Ponte Do Bico', 0, 0, '#3b82f6'),
('46', '46', 'Praça Conde De Agrolongo - Póvoa', 'Praça Conde De Agrolongo', 'Póvoa', 0, 0, '#10b981'),
('50', '50', 'Praça Conde De Agrolongo - Mosteiro De Tibães/Padim Da Graça', 'Praça Conde De Agrolongo', 'Mosteiro De Tibães/Padim Da Graça', 0, 0, '#f59e0b'),
('52', '52', 'Monte D'' Arcos - Merelim (S. Roque)', 'Monte D'' Arcos', 'Merelim (S. Roque)', 0, 0, '#8b5cf6'),
('53', '53', 'Avenida General Norton De Matos - Semelhe/Gondizalves', 'Avenida General Norton De Matos', 'Semelhe/Gondizalves', 0, 0, '#ec4899'),
('54', '54', 'Praça Conde De Agrolongo - Misericórdia', 'Praça Conde De Agrolongo', 'Misericórdia', 0, 0, '#0077b6'),
('57', '57', 'Rua Do Raio - Santa Marta', 'Rua Do Raio', 'Santa Marta', 0, 0, '#ef4444'),
('58', '58', 'Rua Do Raio - Pinheiro Do Bicho Via Ponte Nova', 'Rua Do Raio', 'Pinheiro Do Bicho Via Ponte Nova', 0, 0, '#3b82f6'),
('59', '59', 'Avenida Da Liberdade - Escudeiros Via Esporões', 'Avenida Da Liberdade', 'Escudeiros Via Esporões', 0, 0, '#10b981'),
('60', '60', 'Avenida Da Liberdade - Figueiredo (Sobrado)', 'Avenida Da Liberdade', 'Figueiredo (Sobrado)', 0, 0, '#f59e0b'),
('63', '63', 'Rua 25 De Abril - S. Pedro D'' Este', 'Rua 25 De Abril', 'S. Pedro D'' Este', 0, 0, '#8b5cf6'),
('66', '66', 'Cabreiros - Gualtar', 'Cabreiros', 'Gualtar', 0, 0, '#ec4899'),
('70', '70', 'Rua Do Raio - Trandeiras Via Pinheiro Do Bicho', 'Rua Do Raio', 'Trandeiras Via Pinheiro Do Bicho', 0, 0, '#0077b6'),
('72', '72', 'Avenida Central - Monte Do Ouro', 'Avenida Central', 'Monte Do Ouro', 0, 0, '#ef4444'),
('73', '73', 'Avenida Central - Navarra/Pousada', 'Avenida Central', 'Navarra/Pousada', 0, 0, '#3b82f6'),
('74', '74', 'Camélias - Hospital', 'Camélias', 'Hospital', 0, 0, '#10b981'),
('76', '76', 'Avenida Da Liberdade - Celeirós Via Pinheiro Do Bicho', 'Avenida Da Liberdade', 'Celeirós Via Pinheiro Do Bicho', 0, 0, '#f59e0b'),
('80', '80', 'Sete Fontes - Espírito Santo', 'Sete Fontes', 'Espírito Santo', 0, 0, '#8b5cf6'),
('81', '81', 'Avenida Central - Moínhos Via Adaúfe', 'Avenida Central', 'Moínhos Via Adaúfe', 0, 0, '#ec4899'),
('83', '83', 'Avenida Da Liberdade - Lageosa/Pedralva', 'Avenida Da Liberdade', 'Lageosa/Pedralva', 0, 0, '#0077b6'),
('84', '84', 'Praça Conde De Agrolongo - Ruílhe', 'Praça Conde De Agrolongo', 'Ruílhe', 0, 0, '#ef4444'),
('85', '85', 'Circuito Urbano Iii', 'Circuito Urbano Iii', 'Circuito Urbano Iii', 0, 0, '#3b82f6'),
('87', '87', 'Estação Cf - Hospital', 'Estação Cf', 'Hospital', 0, 0, '#10b981'),
('88', '88', 'Rua Do Raio - Espinho/Sameiro', 'Rua Do Raio', 'Espinho/Sameiro', 0, 0, '#f59e0b'),
('89', '89', 'Gondizalves/Semelhe - Nogueira (Barral)', 'Gondizalves/Semelhe', 'Nogueira (Barral)', 0, 0, '#8b5cf6'),
('90', '90', 'Padim Da Graça - Nogueiró', 'Padim Da Graça', 'Nogueiró', 0, 0, '#ec4899'),
('91', '91', 'Priscos - S. Pedro D'' Este', 'Priscos', 'S. Pedro D'' Este', 0, 0, '#0077b6'),
('92', '92', 'Avenida Central - Monte Do Ouro/Moinhos', 'Avenida Central', 'Monte Do Ouro/Moinhos', 0, 0, '#ef4444'),
('93', '93', 'Avenida Central - Cunha/Arentim', 'Avenida Central', 'Cunha/Arentim', 0, 0, '#3b82f6'),
('94', '94', 'Ponte Pedrinha - Montélios', 'Ponte Pedrinha', 'Montélios', 0, 0, '#10b981'),
('95', '95', 'Minho Center - Nova Arcada', 'Minho Center', 'Nova Arcada', 0, 0, '#f59e0b'),
('96', '96', 'Hotel De Lamaçães - E.Leclerc', 'Hotel De Lamaçães', 'E.Leclerc', 0, 0, '#8b5cf6'),
('97', '97', 'Rua Do Raio - Celeirós', 'Rua Do Raio', 'Celeirós', 0, 0, '#ec4899'),
('98', '98', 'Monte D'' Arcos - Merelim S.Pedro (Eb23 Cávado)', 'Monte D'' Arcos', 'Merelim S.Pedro (Eb23 Cávado)', 0, 0, '#0077b6'),
('99', '99', 'Avenida Central - Santa Lucrécia', 'Avenida Central', 'Santa Lucrécia', 0, 0, '#ef4444'),
('315', '315', 'Avenida Central - Mazagao', 'Avenida Central', 'Mazagao', 0, 0, '#3b82f6'),
('501', '501', 'Avenida Central - Parque Industrial Adaúfe (Via Pintancinhos)', 'Avenida Central', 'Parque Industrial Adaúfe (Via Pintancinhos)', 0, 0, '#10b981'),
('900', '900', 'Avenida Central - Hospital', 'Avenida Central', 'Hospital', 0, 0, '#f59e0b'),
('907', '907', 'Misericórdia - S. Mamede D'' Este', 'Misericórdia', 'S. Mamede D'' Este', 0, 0, '#8b5cf6'),
('911', '911', 'Avenida Central - Padim Da Graça', 'Avenida Central', 'Padim Da Graça', 0, 0, '#ec4899'),
('914', '914', 'Avenida Central - Priscos', 'Avenida Central', 'Priscos', 0, 0, '#0077b6'),
('920', '920', 'Avenida Central - Escudeiros Via Ponte Nova', 'Avenida Central', 'Escudeiros Via Ponte Nova', 0, 0, '#ef4444'),
('928', '928', 'Avenida Central - Navarra', 'Avenida Central', 'Navarra', 0, 0, '#3b82f6'),
('933', '933', 'Avenida Central - Cabreiros', 'Avenida Central', 'Cabreiros', 0, 0, '#10b981'),
('935', '935', 'Avenida Central - Guisande', 'Avenida Central', 'Guisande', 0, 0, '#f59e0b'),
('937', '937', 'Avenida Central - Arentim', 'Avenida Central', 'Arentim', 0, 0, '#8b5cf6'),
('942', '942', 'Universidade Minho - Avenida Central', 'Universidade Minho', 'Avenida Central', 0, 0, '#ec4899'),
('943', '943', 'Estação Cf - Universidade Do Minho', 'Estação Cf', 'Universidade Do Minho', 0, 0, '#0077b6'),
('945', '945', 'Avenida Central - Ponte Do Bico', 'Avenida Central', 'Ponte Do Bico', 0, 0, '#ef4444'),
('949', '949', 'Avenida Central - Ruães', 'Avenida Central', 'Ruães', 0, 0, '#3b82f6'),
('995', '995', 'Minho Center - Nova Arcada', 'Minho Center', 'Nova Arcada', 0, 0, '#10b981')
ON CONFLICT DO NOTHING;
